sudo: required
language: generic
services:
  - docker
os:
  - linux
env:
  global:
    - DOCKER_IMAGE_NAME="backend-project"
    - DOCKER_HUB_ORG="agatharach"
before_script:
  - openssl aes-256-cbc -K $encrypted_b3b81f6772fe_key -iv $encrypted_b3b81f6772fe_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - sudo chmod +x deploy.sh
  - sudo chmod 600 deploy_rsa
  - sudo echo -e "class Config():\n\tpass\nclass DevelopmentConfig(Config):\n\tDEBUG
    = True\n\tSQLALCHEMY_DATABASE_URI = 'mysql+pymysql://admin:${PASSWORD}@cobaevant.cwpvjetmrbmv.ap-southeast-1.rds.amazonaws.com:3306/evant'\n\nclass
    TestingConfig(Config):\n\tTESTING = True\n\tSQLALCHEMY_DATABASE_URI = 'mysql+pymysql://admin:${PASSWORD}@cobaevant.cwpvjetmrbmv.ap-southeast-1.rds.amazonaws.com:3306/evant_test'"
    > config.py
  - echo -e "export FLASK_ENV=testing"
  - echo -e "pytest --cov=blueprints tests"
  - echo -e "export FLASK_ENV=development"
after_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - ls
  - mkdir -p ./storage/log/
  - docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    .
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
  - docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" && docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
before_install:
